version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "Ziedelth"
    reviewers:
      - "Ziedelth"

  - package-ecosystem: "gradle"
    directory: "/android/"
    schedule:
      interval: "daily"
    assignees:
      - "Ziedelth"
    reviewers:
      - "Ziedelth"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "Ziedelth"
    reviewers:
      - "Ziedelth"