name: Pull Request

on:
  pull_request:

jobs:
  test:
    name: Format and Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Get
        run: flutter pub get

      - name: Format
        run: dart format --set-exit-if-changed .

      - name: Dart Analyze
        run: dart analyze

      - name: Check nullable code
        run: flutter pub run dart_code_metrics:metrics check-unnecessary-nullable lib

      - name: Check unused files
        run: flutter pub run dart_code_metrics:metrics check-unused-files lib

      - name: Check unused localizations
        run: flutter pub run dart_code_metrics:metrics check-unused-l10n lib

      - name: Check unused code
        run: flutter pub run dart_code_metrics:metrics check-unused-code lib