name: Test CI/CD

on:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: flutter test

      - name: Format
        run: flutter format --set-exit-if-changed .

      - name: Analyze
        run: flutter analyze